<?php

/**
 * @file
 * coco_link.module
 *
 * @todo Add better file description.
 */

/**
 * Implements hook_node_info().
 */
function coco_link_node_info() {
  return array(
    'link_content' => array(
      'name' => t('Link'),
      'base' => 'node_content',
      'description' => t('Use for creating and referencing link content that can be referenced by other entities.'),
    )
  );
}

/**
 * Implements hook_install().
 */
function coco_link_install() {
  $node_type = 'link_content';

  // Add the body field, just in case we don't have one yet, even though that's
  // unlikely.
  node_add_body_field($node_type, $label = 'Body');

  $default_fields = array();
  if (module_exists('link')) {
    $default_fields['coco_link_field'] = array(
      'field' => array(
        'type' => 'link_field',
      ),
      'instance' => array(
        'label' => $label,
        'widget' => array('type' => 'link_field'),
        'settings' => array('display_summary' => TRUE),
        'display' => array(
          'default' => array(
            'label' => 'hidden',
            'type' => 'text_default',
          ),
          'teaser' => array(
            'label' => 'hidden',
            'type' => 'text_summary_or_trimmed',
          ),
        ),
      ),
    );
  }

  foreach ($default_fields as $field_name => $field_info) {
    if (empty(field_info_field('body'))) {
      $field = $field_info['field'];
      $field += array(
        'field_name' => $field_name,
        'entity_types' => array('node'),
        'bundle' => $node_type,
      );
      field_create_field($field);
    }
    if (empty(field_info_instance('node', $field_name, $node_type))) {
      $instance = $field_info['instance'];
      $instance += array(
        'field_name' => $field_name,
        'entity_type' => 'node',
        'bundle' => $node_type,
      );

      field_create_instance($instance);
    }
  }
}
